"""
Multinode Environmental Sensing Monitor (display only)  -- native/systemd track
- source : SQLite (sensor_data.db) written by hub.py -- read only
- split  : collect (hub.py) <-> display (this file). Same DB file.
- labels : nodes.json (optional; falls back to node ID)

[Presentation layer -- separated from Python]
  static/tokens.css        design tokens (Apple HIG, dark appearance)
  static/app.css           Streamlit chrome (parent document)
  static/vision_panel.css  vision panel styles (components.html iframe)
  static/vision_panel.html vision panel markup template ({{key}} placeholders)
  .streamlit/config.toml   Streamlit base theme

  Python keeps NO style strings. The only exception is Plotly, which cannot
  read CSS -- the SYS dict below mirrors the system colors in tokens.css.
  Change a color in one place -> change it in the other.

[Run]
  uv run streamlit run dashboard.py --server.address 0.0.0.0 --server.headless true

[Deploy]
  On the device this runs as the systemd --user service `mintcap-dashboard`.
  Do not edit this file on the device -- it is a clone of the GitHub repo and
  deploy/deploy.sh resets it to origin/main every minute. Edit, commit and push
  from the repo instead; the service restarts itself once the change lands.

[Screen sections]
  1) node card grid (auto layout) -- radar per node
  2) overall stats (5-min cache) -- boxplots | correlation | targets | regime
  3) time series -- pick a node -> 6 variables in a row
     + per-node regime | vision occupancy crosshair map (2-col)
  4) recent 5 rows
  5) data export -- full CSV / merged CSV / date-range CSV
  6) data reset (backup + clear)
"""
import json, os, re, sqlite3
from contextlib import closing
from datetime import datetime, date, time, timedelta
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

import streamlit as st
import streamlit.components.v1 as components
from streamlit_autorefresh import st_autorefresh

# ---- Config ----
DB         = "sensor_data.db"
NODES_PATH = "nodes.json"
ROW_LIMIT  = 5000          # recent rows to show
REFRESH_MS = 10_000        # auto-refresh every 10s
MAX_COLS   = 4             # max grid columns (2 rows x 4 = 8 nodes)

# Single-room mode. None = show every node found in the DB.
# Set to a list to pin the dashboard to one classroom even if the DB still
# holds rows from other nodes (e.g. ["env-c5f9"] or ["env-c5f9", "vis-9a41"]).
# Node IDs, not labels -- the same keys used in nodes.json.
ONLY_NODES: "list[str] | None" = None

STATIC_DIR = Path(__file__).resolve().parent / "static"


# ========================================================
#  [ASSETS] CSS / HTML loading -- presentation lives in static/
# ========================================================
@st.cache_data(ttl=2)               # short ttl: edit CSS -> visible next refresh
def load_asset(*names: str) -> str:
    """Concatenate static files in order. tokens.css must come first so the
    CSS custom properties are defined before any rule uses them."""
    out = []
    for name in names:
        p = STATIC_DIR / name
        if not p.is_file():
            st.error(f"Missing asset: static/{name}")
            continue
        out.append(p.read_text(encoding="utf-8"))
    return "\n".join(out)


def inject_css(*names: str):
    """Inject stylesheets into the PARENT document (Streamlit page)."""
    st.markdown(f"<style>{load_asset(*names)}</style>", unsafe_allow_html=True)


def render_template(name: str, **ctx) -> str:
    """Fill {{key}} placeholders. Plain replace -- no brace escaping needed,
    so the HTML file stays valid HTML that an editor can lint."""
    html = load_asset(name)
    for k, v in ctx.items():
        html = html.replace("{{" + k + "}}", str(v))
    return html


# ========================================================
#  [PLOTLY COLORS] mirror of :root in static/tokens.css
#  Plotly renders to canvas/SVG and cannot resolve CSS variables,
#  so the palette is duplicated here -- intentionally, and only here.
# ========================================================
SYS = {
    "blue":   "#0A84FF", "green":  "#30D158", "indigo": "#5E5CE6",
    "mint":   "#63E6E2", "orange": "#FF9F0A", "pink":   "#FF375F",
    "purple": "#BF5AF2", "red":    "#FF453A", "teal":   "#64D2FF",
    "yellow": "#FFD60A", "brown":  "#AC8E68", "gray":   "#98989D",
    "cyan":   "#64D2FF",                      # alias of teal
}

# mirror of --font-text (Plotly needs a plain family string)
PLOTLY_FONT = ('-apple-system, BlinkMacSystemFont, "SF Pro Text", '
               '"Apple SD Gothic Neo", Pretendard, sans-serif')

BG        = "#000000"                     # --bg-base
PANEL_BG  = "#1C1C1E"                     # --bg-elevated
INK       = "#FFFFFF"                     # --label-primary
INK_DIM   = "rgba(235,235,245,0.60)"      # --label-secondary
GRID      = "rgba(84,84,88,0.65)"         # --separator

# section header tints
H_OVERVIEW = SYS["teal"]
H_STATS    = SYS["orange"]
H_TS       = SYS["blue"]
H_EXPORT   = SYS["purple"]

# ---- Node identity colors (vivid, deliberately outside the per-variable
#      METRICS hues). Shared by radar + regime scatters. ----
NODE_PALETTE = [SYS["pink"], SYS["indigo"], SYS["mint"], SYS["yellow"],
                SYS["teal"], SYS["green"], SYS["orange"], "#EAEAEA"]  # 8 nodes
NODE_COLOR: dict = {}          # filled once nodes are known (label-number order)


def node_color(node_id: str) -> str:
    return NODE_COLOR.get(node_id, NODE_PALETTE[0])


def node_fill(node_id: str, alpha: float = 0.32) -> str:
    h = node_color(node_id).lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return f"rgba({r},{g},{b},{alpha})"


# ========================================================
#  [METRICS] SEN55 + SCD30 sensor definitions (11 raw vars)
#  format: key:(label, unit, color, gauge_min, gauge_max)
#  Temp/Hum representative = SCD30 (scd_temp/scd_hum). SEN55 T/H kept in DB only.
# ========================================================
METRICS = {
    # SEN55
    "pm1p0":    ("PM1.0",  "\u00b5g/m\u00b3", SYS["pink"],   0,  100),
    "pm2p5":    ("PM2.5",  "\u00b5g/m\u00b3", SYS["orange"], 0,  100),
    "pm4p0":    ("PM4.0",  "\u00b5g/m\u00b3", SYS["brown"],  0,  100),
    "pm10p0":   ("PM10",   "\u00b5g/m\u00b3", SYS["red"],    0,  150),
    "sen_temp": ("Temp(SEN)", "\u00b0C",      SYS["gray"],   0,   50),
    "sen_hum":  ("Hum(SEN)",  "%",            SYS["gray"],   0,  100),
    "voc":      ("VOC",    "idx",             SYS["green"],  0,  500),
    "nox":      ("NOx",    "idx",             SYS["purple"], 0,  500),
    # SCD30
    "co2":      ("CO\u2082", "ppm",           SYS["teal"],   400, 2000),
    "scd_temp": ("Temp",   "\u00b0C",         SYS["yellow"], 0,   50),
    "scd_hum":  ("Hum",    "%",               SYS["blue"],   0,  100),
}
# all 11 vars stored in DB; ALL_KEYS used for export (full raw)
ALL_KEYS = list(METRICS.keys())

# Displayed vars (6): CO2 + SCD30 temp/hum + PM2.5/PM10 + VOC.
# Hidden from display (DB/export only): pm1p0, pm4p0, nox, sen_temp, sen_hum.
# CO2 and VOC are ML targets -> placed LAST with emphasis.
GAUGE_KEYS = ["pm2p5", "pm10p0", "scd_temp", "scd_hum", "co2", "voc"]
STATS_KEYS = ["pm2p5", "pm10p0", "scd_temp", "scd_hum", "co2", "voc"]
TS_KEYS    = ["pm2p5", "pm10p0", "scd_temp", "scd_hum", "co2", "voc"]
SENSOR_KEYS = ALL_KEYS    # backward-compat alias (export uses all 11)

# ML-target emphasis (CO2 & VOC). Both highlighted at the end of charts.
TARGET_KEYS   = ["co2", "voc"]
VOC_EMPH_BG   = "rgba(48,209,88,0.12)"     # systemGreen tint (VOC)
VOC_EMPH_LINE = SYS["green"]
CO2_EMPH_BG   = "rgba(100,210,255,0.12)"   # systemTeal tint (CO2)
CO2_EMPH_LINE = SYS["teal"]


def emph_line(key):  return CO2_EMPH_LINE if key == "co2" else VOC_EMPH_LINE
def emph_bg(key):    return CO2_EMPH_BG if key == "co2" else VOC_EMPH_BG


# ---- Rule-based air-quality color grade (NOT ML; based on public guidelines) ----
#  Returns (grade_text, color). Conservative thresholds for indoor reference.
#  PM2.5/PM10 ~ KR MoE bands ; VOC/NOx index 100 = 24h baseline.
def grade_color(key: str, v):
    if v is None or pd.isna(v):
        return ("-", INK_DIM)
    good, mod, bad = SYS["green"], SYS["yellow"], SYS["red"]
    if key == "pm2p5":
        return ("good", good) if v <= 15 else ("moderate", mod) if v <= 35 else ("bad", bad)
    if key == "pm10p0":
        return ("good", good) if v <= 30 else ("moderate", mod) if v <= 80 else ("bad", bad)
    if key in ("voc", "nox"):     # index: 100 = 24h average baseline
        return ("good", good) if v <= 100 else ("moderate", mod) if v <= 200 else ("bad", bad)
    if key == "temp":
        return ("good", good) if 18 <= v <= 26 else ("moderate", mod) if 15 <= v <= 30 else ("bad", bad)
    if key == "hum":
        return ("good", good) if 40 <= v <= 60 else ("moderate", mod) if 30 <= v <= 70 else ("bad", bad)
    return ("-", INK_DIM)


# ---- Data loading ----
@st.cache_data(ttl=5)
def load_df(limit: int = ROW_LIMIT) -> pd.DataFrame:
    """Recent rows from SQLite -> KST time. SEN55 stores values directly (no scaling)."""
    if not os.path.isfile(DB):
        return pd.DataFrame()
    sql = ("SELECT datetime(ts,'+9 hours') AS recv_time, node, "
           "pm1p0, pm2p5, pm4p0, pm10p0, sen_temp, sen_hum, voc, nox, "
           "co2, scd_temp, scd_hum "
           "FROM readings ORDER BY id DESC LIMIT ?")
    with closing(sqlite3.connect(DB)) as con:
        df = pd.read_sql_query(sql, con, params=(limit,))
    return df.iloc[::-1].reset_index(drop=True) if not df.empty else df


@st.cache_data(ttl=300)               # stats cached for 5 min
def load_all_for_stats() -> pd.DataFrame:
    if not os.path.isfile(DB):
        return pd.DataFrame()
    sql = ("SELECT node, pm1p0, pm2p5, pm4p0, pm10p0, sen_temp, sen_hum, voc, nox, "
           "co2, scd_temp, scd_hum "
           "FROM readings")
    with closing(sqlite3.connect(DB)) as con:
        return pd.read_sql_query(sql, con)


def query_range(start_kst: datetime, end_kst: datetime) -> pd.DataFrame:
    """For date-range export. DB stores UTC; subtract 9h from KST range."""
    if not os.path.isfile(DB):
        return pd.DataFrame()
    start_utc = (start_kst - timedelta(hours=9)).strftime("%Y-%m-%d %H:%M:%S")
    end_utc   = (end_kst   - timedelta(hours=9)).strftime("%Y-%m-%d %H:%M:%S")
    sql = ("SELECT datetime(ts,'+9 hours') AS recv_time_kst, node, "
           "pm1p0, pm2p5, pm4p0, pm10p0, sen_temp, sen_hum, voc, nox, "
           "co2, scd_temp, scd_hum "
           "FROM readings WHERE ts BETWEEN ? AND ? ORDER BY id")
    with closing(sqlite3.connect(DB)) as con:
        return pd.read_sql_query(sql, con, params=(start_utc, end_utc))


def get_time_bounds():
    """Min/max time in DB (KST) -- defaults for the range picker."""
    if not os.path.isfile(DB):
        return None, None
    sql = ("SELECT MIN(datetime(ts,'+9 hours')), MAX(datetime(ts,'+9 hours')) "
           "FROM readings")
    with closing(sqlite3.connect(DB)) as con:
        lo, hi = con.execute(sql).fetchone()
    if not lo:
        return None, None
    return (datetime.fromisoformat(lo), datetime.fromisoformat(hi))


def load_node_labels() -> dict:
    if not os.path.isfile(NODES_PATH):
        return {}
    try:
        with open(NODES_PATH, encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        st.warning(f"nodes.json read error: {e}")
        return {}


def label_of(node_id: str, labels: dict) -> str:
    return labels.get(node_id, node_id)


# ========================================================
#  [VISION] FOMO occupancy node (Nicla) -- `occupancy` table
#  - source : hub.py stores topic multinode_aq/+/occ
#  - pairing: env node <-> vision node share the SAME label in nodes.json
#  - policy : occ* columns = analysis (SQL/join) ; cents JSON = UI only
# ========================================================
def _occ_table_exists() -> bool:
    if not os.path.isfile(DB):
        return False
    with closing(sqlite3.connect(DB)) as con:
        r = con.execute("SELECT name FROM sqlite_master "
                        "WHERE type='table' AND name='occupancy'").fetchone()
    return bool(r)


@st.cache_data(ttl=5)
def load_occ_latest() -> pd.DataFrame:
    """Last bucket per vision node (+9h KST time)."""
    if not _occ_table_exists():
        return pd.DataFrame()
    sql = ("SELECT o.node, datetime(o.ts,'+9 hours') AS recv_time, "
           "o.occ, o.occ_med, o.occ_max, o.occ_last, o.cents, o.w, o.n "
           "FROM occupancy o JOIN (SELECT node, MAX(id) AS mid FROM occupancy "
           "GROUP BY node) m ON o.id = m.mid")
    with closing(sqlite3.connect(DB)) as con:
        return pd.read_sql_query(sql, con)


@st.cache_data(ttl=5)
def load_occ_hist(node_id: str, limit: int = 24) -> pd.DataFrame:
    """Recent buckets for the mini bar strip (oldest -> newest)."""
    if not _occ_table_exists():
        return pd.DataFrame()
    sql = ("SELECT datetime(ts,'+9 hours') AS recv_time, occ, occ_max, n "
           "FROM occupancy WHERE node=? ORDER BY id DESC LIMIT ?")
    with closing(sqlite3.connect(DB)) as con:
        df = pd.read_sql_query(sql, con, params=(node_id, limit))
    return df.iloc[::-1].reset_index(drop=True)


def vision_node_for(env_node: str, labels: dict, occ_nodes) -> "str | None":
    """Find the vision node sharing this env node's label (nodes.json pairing)."""
    lbl = label_of(env_node, labels)
    for vn in occ_nodes:
        if label_of(vn, labels) == lbl:
            return vn
    return None


@st.cache_data(ttl=60)
def load_merged_analysis(min_n_env: int = 0, min_n_occ: int = 25) -> pd.DataFrame:
    """Analysis-ready dataframe: env(readings) x vision(occupancy) merged on
    (bucket ts, room label). Exact join -- both sides publish on the same
    NTP-aligned bucket grid, so no resample/asof needed. Rows whose occ bucket
    has too few samples (n < min_n_occ) are dropped as low-quality."""
    if not _occ_table_exists():
        return pd.DataFrame()
    labels_ = load_node_labels()
    with closing(sqlite3.connect(DB)) as con:
        env = pd.read_sql_query(
            "SELECT ts, node, co2, voc, scd_temp, scd_hum, pm2p5, pm10p0, n "
            "FROM readings", con)
        occ = pd.read_sql_query(
            "SELECT ts, node, occ AS occ_mean, occ_med, occ_max, n AS occ_n "
            "FROM occupancy WHERE n >= ?", con, params=(min_n_occ,))
    if env.empty or occ.empty:
        return pd.DataFrame()
    env["room"] = env["node"].map(labels_)
    occ["room"] = occ["node"].map(labels_)
    env = env.dropna(subset=["room"])
    occ = occ.dropna(subset=["room"])
    m = pd.merge(env.drop(columns=["node"]),
                 occ[["ts", "room", "occ_mean", "occ_med", "occ_max", "occ_n"]],
                 on=["ts", "room"], how="inner")
    if m.empty:
        return m
    m["t_kst"] = (pd.to_datetime(m["ts"]) + pd.Timedelta(hours=9)
                  ).dt.strftime("%Y-%m-%d %H:%M:%S")
    cols = ["t_kst", "room", "co2", "voc", "scd_temp", "scd_hum",
            "pm2p5", "pm10p0", "occ_mean", "occ_med", "occ_max", "occ_n"]
    return m[cols].sort_values(["room", "t_kst"]).reset_index(drop=True)


def render_vision_panel(env_node: str, labels: dict):
    """Section-3 right column: blinking-crosshair occupancy map for the vision
    node paired (same label) with the selected env node.
    Markup -> static/vision_panel.html, styles -> static/vision_panel.css.
    Only data-derived geometry (crosshair x/y, bar height) stays inline."""
    lbl = label_of(env_node, labels)
    occ_latest = load_occ_latest()
    if occ_latest.empty:
        st.info("비전(재실) 데이터가 아직 없습니다 — occ 노드 발행과 "
                "hub.py의 occ 구독(occupancy 테이블)을 확인하세요.")
        return
    vn = vision_node_for(env_node, labels, occ_latest["node"].tolist())
    if vn is None:
        st.info(f"'{lbl}' 교실에 매핑된 비전 노드가 없습니다. "
                "nodes.json에서 비전 노드 ID를 같은 라벨로 등록하세요.")
        return

    row = occ_latest[occ_latest["node"] == vn].iloc[0]
    try:
        cents = json.loads(row["cents"] or "[]")
    except Exception:
        cents = []
    w = int(row["w"]) if row["w"] else 96
    hist = load_occ_hist(vn)

    # freshness: bucket older than ~12 min -> stale badge
    stale = True
    try:
        age = datetime.now() - datetime.fromisoformat(str(row["recv_time"]))
        stale = age > timedelta(minutes=12)
    except Exception:
        pass
    status_class = "vp__status vp__status--stale" if stale else "vp__status"
    status_text  = "지연" if stale else "LIVE"

    # crosshairs (staggered blink for visual rhythm)
    ch = ""
    for i, c in enumerate(cents):
        try:
            x = float(c[0]) / w * 100.0
            y = float(c[1]) / w * 100.0
        except Exception:
            continue
        ch += (f"<div class='vp__ch' style='left:{x:.1f}%;top:{y:.1f}%;"
               f"animation-delay:{i * 0.15:.2f}s'>"
               "<span class='vp__ch-ring'></span>"
               "<span class='vp__ch-dot'></span></div>")
    if not ch:
        ch = "<div class='vp__map-empty'>버킷 내 탐지 없음</div>"

    # history mini bars (scaled by occ_max of the window)
    bars = ""
    if not hist.empty:
        top = max(float(hist["occ_max"].max() or 0), 1.0)
        vals = hist["occ"].fillna(0).tolist()
        for j, v in enumerate(vals):
            hpc = max(3, int(float(v) / top * 100))
            cls = "vp__bar is-now" if j == len(vals) - 1 else "vp__bar"
            bars += f"<i class='{cls}' style='height:{hpc}%'></i>"

    def val(x):
        return "-" if x is None or pd.isna(x) else x

    html = render_template(
        "vision_panel.html",
        label=lbl,
        node=vn,
        status_class=status_class,
        status_text=status_text,
        occ_mean=(f"{float(row['occ']):.1f}" if row["occ"] is not None else "-"),
        occ_med=val(row["occ_med"]),
        occ_max=val(row["occ_max"]),
        n=val(row["n"]),
        crosshairs=ch,
        w=w,
        bars=bars,
        bucket_time=row["recv_time"],
    )
    css = load_asset("tokens.css", "vision_panel.css")
    components.html(f"<style>{css}</style>{html}", height=470, scrolling=False)


# ---- Normalize / charts (Plotly: colors come from SYS, see note above) ----
def normalize(key: str, value):
    _, _, _, gmin, gmax = METRICS[key]
    if gmax == gmin or pd.isna(value):
        return 0.0
    return float(np.clip((value - gmin) / (gmax - gmin), 0.0, 1.0))


def make_node_radar(vals: dict, node_id: str = "") -> go.Figure:
    """Node live status: one radar over GAUGE_KEYS, each var normalized 0-1
    by its METRICS (gmin, gmax) range. Axis label shows name + current value."""
    cats, r = [], []
    for k in GAUGE_KEYS:
        label, unit, _, gmin, gmax = METRICS[k]
        v = vals.get(k)
        if v is None or pd.isna(v):
            rv, vtxt = 0.0, "-"
        else:
            rv = float(np.clip((float(v) - gmin) / (gmax - gmin), 0.0, 1.0))
            vtxt = f"{float(v):.1f}"
        cats.append(f"{label}<br><b>{vtxt}</b> {unit}")
        r.append(rv)
    cats.append(cats[0]); r.append(r[0])          # close polygon
    fig = go.Figure(go.Scatterpolar(
        r=r, theta=cats, fill="toself", mode="lines+markers",
        line=dict(color=node_color(node_id), width=2),
        marker=dict(size=4, color=node_color(node_id)),
        fillcolor=node_fill(node_id),
        hoverinfo="skip", showlegend=False,
    ))
    fig.update_layout(
        height=300, margin=dict(l=56, r=56, t=30, b=26),
        paper_bgcolor="rgba(0,0,0,0)", font={"color": INK, "family": PLOTLY_FONT},
        polar=dict(
            bgcolor="rgba(255,255,255,0.03)",
            radialaxis=dict(range=[0, 1], showticklabels=False,
                            gridcolor=GRID, linecolor=GRID),
            angularaxis=dict(tickfont={"size": 10, "color": INK},
                             gridcolor=GRID, linecolor=GRID),
        ),
    )
    return fig


def node_card(node_id: str, vals: dict, labels: dict):
    with st.container(border=True):
        st.markdown(
            f"<div class='node-card__title'>{label_of(node_id, labels)}</div>"
            f"<div class='node-card__sub'>{node_id}</div>",
            unsafe_allow_html=True)
        # one radar per node (6 vars normalized by gauge range)
        st.plotly_chart(make_node_radar(vals, node_id),
                        use_container_width=True, key=f"radar_{node_id}")


def make_boxplots(dfa: pd.DataFrame) -> go.Figure:
    """Per-variable boxplots (PM1.0/PM4.0 excluded). CO2/VOC last, emphasized."""
    keys = STATS_KEYS
    fig = make_subplots(rows=1, cols=len(keys),
                        subplot_titles=[METRICS[k][0] for k in keys])
    for i, key in enumerate(keys, start=1):
        _, unit, color, _, _ = METRICS[key]
        is_target = key in TARGET_KEYS
        fig.add_trace(go.Box(y=dfa[key], name=METRICS[key][0],
                             marker_color=color, boxpoints="outliers",
                             line={"color": color},
                             fillcolor=(emph_line(key) if is_target else "rgba(255,255,255,0.05)"),
                             showlegend=False), row=1, col=i)
        fig.update_yaxes(title_text=unit, row=1, col=i,
                         title_font={"size": 10, "color": INK_DIM},
                         gridcolor=GRID, tickfont={"color": INK_DIM})
    fig.update_layout(height=300, margin=dict(l=10, r=10, t=40, b=10),
                      paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
                      font={"color": INK, "family": PLOTLY_FONT})
    fig.update_annotations(font_size=12, font_color=INK_DIM)
    anns = fig.layout.annotations
    for i, key in enumerate(keys):
        if key in TARGET_KEYS and i < len(anns):
            anns[i].font.color = emph_line(key)
            anns[i].text = f"{METRICS[key][0]} \u2605"   # star marks target
    return fig


def make_corr(dfa: pd.DataFrame) -> go.Figure:
    corr = dfa[STATS_KEYS].corr()
    labels_x = [METRICS[k][0] for k in STATS_KEYS]
    # diverging scale: systemRed <-> neutral <-> systemBlue
    fig = go.Figure(go.Heatmap(
        z=corr.values, x=labels_x, y=labels_x,
        text=np.round(corr.values, 2), texttemplate="%{text}",
        textfont={"color": "#1C1C1E"},
        colorscale=[[0.0, SYS["red"]], [0.5, "#E5E5EA"], [1.0, SYS["blue"]]],
        zmid=0, zmin=-1, zmax=1,
        colorbar=dict(title="r", tickfont={"color": INK_DIM}), xgap=2, ygap=2,
    ))
    fig.update_layout(height=300, margin=dict(l=10, r=10, t=30, b=10),
                      title=dict(text="Correlation", x=0.5, xanchor="center",
                                 font=dict(size=12, color=INK_DIM)),
                      paper_bgcolor="rgba(0,0,0,0)",
                      font={"color": INK, "family": PLOTLY_FONT},
                      xaxis=dict(tickfont={"size": 9, "color": INK_DIM}, automargin=True),
                      yaxis=dict(tickfont={"size": 9, "color": INK_DIM}, automargin=True))
    fig.update_traces(textfont_size=9)   # cell numbers smaller for narrow column
    return fig


def make_target_by_node(dfa: pd.DataFrame, labels: dict, key: str) -> go.Figure:
    """Mean value of an ML-target var (co2 or voc) per node, highest first.
    Tone gradation: higher value -> deeper color (VOC=green, CO2=teal)."""
    g = (dfa.groupby("node")[key].mean()
         .sort_values(ascending=False))            # highest first
    names = [label_of(n, labels) for n in g.index]
    vals = g.values
    n = len(vals)
    vmax = float(vals.max()) if n and vals.max() > 0 else 1.0
    vmin = float(vals.min()) if n else 0.0
    if key == "co2":
        lo, hi = (100, 210, 255), (10, 90, 130)    # systemTeal -> deep teal
    else:  # voc
        lo, hi = (48, 209, 88), (16, 92, 44)       # systemGreen -> deep green
    def grad(v):
        t = 0.5 if vmax == vmin else (v - vmin) / (vmax - vmin)
        r = int(lo[0] + (hi[0] - lo[0]) * t)
        gg = int(lo[1] + (hi[1] - lo[1]) * t)
        b = int(lo[2] + (hi[2] - lo[2]) * t)
        return f"rgb({r},{gg},{b})"
    colors = [grad(v) for v in vals]
    label, unit, _, _, _ = METRICS[key]
    fig = go.Figure(go.Bar(
        x=names, y=vals, orientation="v",
        marker_color=colors,
        text=[f"{v:.0f}" for v in vals], textposition="outside",
        showlegend=False,
    ))
    fig.update_layout(
        height=215, margin=dict(l=10, r=20, t=28, b=28),
        title=dict(text=f"{label} by node \u2605", x=0.5, xanchor="center",
                   font=dict(size=12, color=emph_line(key))),
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor=emph_bg(key),
        font={"color": INK, "family": PLOTLY_FONT},
        xaxis=dict(tickfont={"size": 10, "color": INK_DIM}, automargin=True),
        yaxis=dict(title=f"{label} ({unit})", gridcolor=GRID,
                   tickfont={"color": INK_DIM},
                   title_font={"size": 10, "color": INK_DIM}),
        bargap=0.35,
    )
    return fig


def make_regime_scatter(dfa: pd.DataFrame, labels: dict, latest: dict = None) -> go.Figure:
    """CO2-VOC RELATIVE regime scatter (RobustScaling). Each point = one reading.
    RobustScaling: (v - median) / IQR -> robust to outliers & skew, stable origin.
    NOTE: normalization removes ABSOLUTE level; absolute level = CO2 barplot.
    v2: past-point scatter removed -> density bg + current vectors only."""
    d = dfa[["co2", "voc", "node"]].dropna()
    if len(d) < 3:
        fig = go.Figure()
        fig.add_annotation(text="Not enough data yet for regime scatter",
                           x=0.5, y=0.5, showarrow=False, font={"color": INK_DIM})
        fig.update_layout(height=420, paper_bgcolor="rgba(0,0,0,0)",
                          plot_bgcolor="rgba(0,0,0,0)",
                          font={"color": INK, "family": PLOTLY_FONT})
        return fig

    def robust(s):
        med = s.median()
        iqr = s.quantile(0.75) - s.quantile(0.25)
        return (s - med) / iqr if iqr and iqr > 0 else (s - med) * 0.0
    zco2 = robust(d["co2"]); zvoc = robust(d["voc"])

    fig = go.Figure()
    co2_med = d["co2"].median(); co2_iqr = d["co2"].quantile(0.75) - d["co2"].quantile(0.25)
    voc_med = d["voc"].median(); voc_iqr = d["voc"].quantile(0.75) - d["voc"].quantile(0.25)
    def rc(v, med, iqr): return (v - med) / iqr if iqr and iqr > 0 else 0.0

    def prange(s):
        lo, hi = s.quantile(0.02), s.quantile(0.98)
        return max(abs(lo), abs(hi))
    amax = float(max(prange(zco2), prange(zvoc)))
    amax = (amax * 1.15) if amax > 0 else 1.0
    amax = min(max(amax, 1.5), 3.0)       # 1.5~3.0 (max 3 grid at dtick=1)

    def clip(v):
        return max(-amax, min(amax, v))

    fig.add_trace(go.Histogram2d(
        x=zco2.clip(-amax, amax), y=zvoc.clip(-amax, amax),
        nbinsx=24, nbinsy=24,
        colorscale=[[0.0, "rgba(0,0,0,0)"], [0.15, "rgba(10,132,255,0.10)"],
                    [0.5, "rgba(10,132,255,0.28)"], [1.0, "rgba(10,132,255,0.55)"]],
        showscale=False, zsmooth="best", hoverinfo="skip",
    ))

    node_list = sorted(d["node"].unique(), key=lambda n: labels.get(n, n))
    # 과거 개별 산점은 제거 — 분포 맥락은 밀도 배경(Histogram2d)만 유지 (가독성)
    if latest:
        for i, nd in enumerate(node_list):
            cur = latest.get(nd)
            if not cur:
                continue
            cv, vv = cur.get("co2"), cur.get("voc")
            if cv is None or vv is None or pd.isna(cv) or pd.isna(vv):
                continue
            rx, ry = rc(cv, co2_med, co2_iqr), rc(vv, voc_med, voc_iqr)
            cx, cy = clip(rx), clip(ry)          # clip into view; flag if outside
            outside = (cx != rx) or (cy != ry)
            col = node_color(nd)
            fig.add_annotation(x=cx, y=cy, ax=0, ay=0,
                               xref="x", yref="y", axref="x", ayref="y",
                               showarrow=True, arrowhead=2, arrowsize=1.0,
                               arrowwidth=2, arrowcolor=col, opacity=0.95)
            fig.add_trace(go.Scatter(
                x=[cx], y=[cy], mode="markers",
                name=f"{label_of(nd, labels)} (now)", legendgroup=nd,
                showlegend=False,
                marker=dict(size=16, color=col,
                            symbol=("diamond-open" if outside else "star"),
                            line=dict(width=1.6, color=INK)),
                hovertemplate=(f"{label_of(nd, labels)} now<br>CO2 r=%{{x:.2f}}"
                               f"<br>VOC r=%{{y:.2f}}"
                               f"{' (범위밖)' if outside else ''}<extra></extra>"),
            ))
            norm = (cx * cx + cy * cy) ** 0.5
            ux, uy = ((cx / norm, cy / norm) if norm > 1e-6 else (1.0, 0.0))
            off = amax * 0.07
            lx = max(-amax * 0.98, min(amax * 0.98, cx + ux * off))
            ly = max(-amax * 0.98, min(amax * 0.98, cy + uy * off))
            fig.add_annotation(x=lx, y=ly, text=label_of(nd, labels),
                               showarrow=False,
                               xanchor=("left" if ux >= 0 else "right"),
                               yanchor=("bottom" if uy >= 0 else "top"),
                               font={"size": 9, "color": col},
                               bgcolor="rgba(0,0,0,0.45)",
                               bordercolor=col, borderwidth=1, borderpad=1,
                               opacity=0.95)
    qlabels = [( amax*0.6,  amax*0.6, "Human \u2248 Matter"),
               (-amax*0.6,  amax*0.6, "Matter \u003e Human"),
               ( amax*0.6, -amax*0.6, "Human \u003e Matter"),
               (-amax*0.6, -amax*0.6, "Clean")]
    for qx, qy, qt in qlabels:
        fig.add_annotation(x=qx, y=qy, text=qt, showarrow=False,
                           font={"size": 11, "color": INK})
    fig.update_layout(
        height=440, margin=dict(l=10, r=10, t=36, b=40),
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font={"color": INK, "family": PLOTLY_FONT},
        xaxis=dict(title="CO\u2082 (robust)  \u2192 Human factor", gridcolor=GRID, dtick=1,
                   tickfont={"color": INK_DIM}, range=[-amax, amax],
                   zeroline=True, zerolinecolor=INK, zerolinewidth=2,
                   showline=True, linecolor=INK_DIM, mirror=True),
        yaxis=dict(title="VOC (robust)  \u2192 Matter factor", gridcolor=GRID, dtick=1,
                   tickfont={"color": INK_DIM}, range=[-amax, amax],
                   zeroline=True, zerolinecolor=INK, zerolinewidth=2,
                   showline=True, linecolor=INK_DIM, mirror=True),
        legend=dict(font={"size": 12, "color": INK_DIM}, orientation="h",
                    yanchor="bottom", y=1.02, xanchor="right", x=1),
    )
    return fig


def make_node_regime_scatter(dfa: pd.DataFrame, node_id: str, labels: dict,
                             latest: dict = None) -> go.Figure:
    """Per-node regime scatter using THAT NODE's own median/IQR (within-node
    RobustScaling). 'Is this room different from its OWN baseline?'"""
    d = dfa[dfa["node"] == node_id][["co2", "voc"]].dropna()
    nm = label_of(node_id, labels)
    if len(d) < 3:
        fig = go.Figure()
        fig.add_annotation(text=f"{nm}: not enough data yet",
                           x=0.5, y=0.5, showarrow=False, font={"color": INK_DIM})
        fig.update_layout(height=360, paper_bgcolor="rgba(0,0,0,0)",
                          plot_bgcolor="rgba(0,0,0,0)",
                          font={"color": INK, "family": PLOTLY_FONT})
        return fig

    def robust(s):
        med = s.median(); iqr = s.quantile(0.75) - s.quantile(0.25)
        return ((s - med) / iqr if iqr and iqr > 0 else (s - med) * 0.0), med, iqr
    zco2, co2_med, co2_iqr = robust(d["co2"])
    zvoc, voc_med, voc_iqr = robust(d["voc"])

    fig = go.Figure()
    def prange(s):
        return max(abs(s.quantile(0.02)), abs(s.quantile(0.98)))
    amax = float(max(prange(zco2), prange(zvoc)))
    amax = min(max((amax * 1.15) if amax > 0 else 1.0, 1.5), 3.0)
    def clip(v): return max(-amax, min(amax, v))

    fig.add_trace(go.Histogram2d(
        x=zco2.clip(-amax, amax), y=zvoc.clip(-amax, amax), nbinsx=20, nbinsy=20,
        colorscale=[[0.0, "rgba(0,0,0,0)"], [0.2, "rgba(10,132,255,0.12)"],
                    [0.6, "rgba(10,132,255,0.30)"], [1.0, "rgba(10,132,255,0.55)"]],
        showscale=False, zsmooth="best", hoverinfo="skip",
    ))
    fig.add_trace(go.Scatter(
        x=zco2.clip(-amax, amax), y=zvoc.clip(-amax, amax), mode="markers",
        marker=dict(size=5, color=node_color(node_id),
                    line=dict(width=0.3, color="rgba(0,0,0,0.3)"), opacity=0.4),
        showlegend=False, hoverinfo="skip",
    ))
    def rc(v, med, iqr): return (v - med) / iqr if iqr and iqr > 0 else 0.0
    if latest and latest.get(node_id):
        cur = latest[node_id]
        cv, vv = cur.get("co2"), cur.get("voc")
        if cv is not None and vv is not None and not pd.isna(cv) and not pd.isna(vv):
            rx, ry = rc(cv, co2_med, co2_iqr), rc(vv, voc_med, voc_iqr)
            cx, cy = clip(rx), clip(ry)
            outside = (cx != rx) or (cy != ry)
            fig.add_annotation(x=cx, y=cy, ax=0, ay=0, xref="x", yref="y",
                               axref="x", ayref="y", showarrow=True, arrowhead=2,
                               arrowsize=1.2, arrowwidth=2,
                               arrowcolor=SYS["orange"], opacity=0.9)
            fig.add_trace(go.Scatter(
                x=[cx], y=[cy], mode="markers", showlegend=False,
                marker=dict(size=12, color=SYS["orange"],
                            symbol=("diamond-open" if outside else "star"),
                            line=dict(width=1.2, color=INK)),
                hovertemplate=f"{nm} now<br>CO2 r=%{{x:.2f}}<br>VOC r=%{{y:.2f}}"
                              f"{' (out)' if outside else ''}<extra></extra>",
            ))
    for qx, qy, qt in [( amax*0.6,  amax*0.6, "Human \u2248 Matter"),
                       (-amax*0.6,  amax*0.6, "Matter \u003e Human"),
                       ( amax*0.6, -amax*0.6, "Human \u003e Matter"),
                       (-amax*0.6, -amax*0.6, "Clean")]:
        fig.add_annotation(x=qx, y=qy, text=qt, showarrow=False,
                           font={"size": 10, "color": INK_DIM})
    fig.update_layout(
        height=360, margin=dict(l=10, r=10, t=34, b=36),
        title=dict(text=f"{nm} \u2014 자기 기준 레짐 (within-node Robust)",
                   x=0.5, xanchor="center", font=dict(size=12, color=INK)),
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font={"color": INK, "family": PLOTLY_FONT},
        xaxis=dict(title="CO\u2082 (robust)", gridcolor=GRID, dtick=1, range=[-amax, amax],
                   tickfont={"color": INK_DIM}, zeroline=True, zerolinecolor=INK,
                   zerolinewidth=2, showline=True, linecolor=INK_DIM, mirror=True),
        yaxis=dict(title="VOC (robust)", gridcolor=GRID, dtick=1, range=[-amax, amax],
                   tickfont={"color": INK_DIM}, zeroline=True, zerolinecolor=INK,
                   zerolinewidth=2, showline=True, linecolor=INK_DIM, mirror=True),
    )
    return fig


def make_timeseries(dfn: pd.DataFrame) -> go.Figure:
    keys = TS_KEYS
    fig = make_subplots(rows=1, cols=len(keys),
                        subplot_titles=[f"{METRICS[k][0]} ({METRICS[k][1]})"
                                        for k in keys])
    for i, key in enumerate(keys, start=1):
        color = METRICS[key][2]
        is_target = key in TARGET_KEYS
        fig.add_trace(go.Scatter(
            x=dfn["recv_time"], y=dfn[key], mode="lines+markers",
            line=dict(color=color, width=3 if is_target else 2, shape="spline",
                      smoothing=0.4),
            marker=dict(size=5 if is_target else 4),
            showlegend=False), row=1, col=i)
        fig.update_yaxes(gridcolor=GRID, tickfont={"color": INK_DIM}, row=1, col=i)
        fig.update_xaxes(gridcolor=GRID, row=1, col=i)
    fig.update_layout(height=280, margin=dict(l=10, r=10, t=40, b=40),
                      paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
                      font={"color": INK, "family": PLOTLY_FONT})
    fig.update_xaxes(tickangle=-45, tickfont=dict(size=8, color=INK_DIM))
    fig.update_annotations(font_size=11, font_color=INK_DIM)
    anns = fig.layout.annotations
    for i, key in enumerate(keys):
        if key in TARGET_KEYS and i < len(anns):
            anns[i].font.color = emph_line(key)
    return fig


# ========================================================
#  Screen
# ========================================================
st.set_page_config(page_title="Sensing Monitor", page_icon="◍", layout="wide")
st_autorefresh(interval=REFRESH_MS, key="auto")

# all page styling comes from static/ -- no <style> literals in Python
inject_css("tokens.css", "app.css")

st.markdown("<h1 class='app-title'>Multinode Environmental Sensing Monitor</h1>",
            unsafe_allow_html=True)

df = load_df()
if df.empty:
    st.info("No data yet. Check that the hub (hub.py) is running and that nodes "
            "are publishing. First data appears at the next publish "
            "interval (e.g. every 5 min).")
    st.stop()

labels = load_node_labels()


def _node_sort_key(node_id: str):
    """Sort by integer found in the label (e.g. CLASS_1 -> 1, CLASS_10 -> 10)."""
    lbl = label_of(node_id, labels)
    m = re.search(r"\d+", lbl)
    if m:
        return (0, int(m.group()), lbl.lower())
    return (1, 0, lbl.lower())


if ONLY_NODES:                       # single-room mode: ignore other nodes
    df = df[df["node"].isin(ONLY_NODES)]
    if df.empty:
        st.error(f"ONLY_NODES={ONLY_NODES} matched no rows. "
                 "Check the node IDs against nodes.json.")
        st.stop()

nodes = sorted(df["node"].dropna().unique(), key=_node_sort_key)
SINGLE = len(nodes) == 1
NODE_COLOR.update({n: NODE_PALETTE[i % len(NODE_PALETTE)] for i, n in enumerate(nodes)})
latest = {n: df[df["node"] == n].iloc[-1].to_dict() for n in nodes}

st.markdown(
    f"<p class='app-subtitle'>{len(nodes)} nodes · "
    f"{', '.join(label_of(n, labels) for n in nodes)} &nbsp;|&nbsp; "
    f"{len(df):,} rows · last seen {df['recv_time'].max()} KST</p>",
    unsafe_allow_html=True)


def header(index: str, title: str, tone: str):
    """Section header. `tone` selects a CSS modifier (.sec-h--<tone>);
    the actual color lives in static/app.css, not here."""
    st.markdown(
        f"<div class='sec-h sec-h--{tone}'>"
        f"<span class='sec-h__index'>{index}</span>"
        f"<span class='sec-h__title'>{title}</span></div>",
        unsafe_allow_html=True)


# ---- Section 1: node card grid ----
header("01", "Live status by node", "overview")
if SINGLE:
    # one classroom -> a full-width card would stretch the radar; keep it centred
    _, mid, _ = st.columns([1, 2, 1])
    with mid:
        node_card(nodes[0], latest[nodes[0]], labels)
else:
    ncols = min(len(nodes), MAX_COLS)
    for i in range(0, len(nodes), ncols):
        row_nodes = nodes[i:i + ncols]
        cols = st.columns(ncols)
        for col, node in zip(cols, row_nodes):
            with col:
                node_card(node, latest[node], labels)

# ---- Section 2: overall stats (5-min) ----
header("02", "Overall stats (5-min cache)", "stats")
dfa = load_all_for_stats()
if ONLY_NODES and not dfa.empty:
    dfa = dfa[dfa["node"].isin(ONLY_NODES)]
if not dfa.empty:
    # row 1: boxplot | correlation  (1:1)
    r1c1, r1c2 = st.columns(2)
    r1c1.plotly_chart(make_boxplots(dfa), use_container_width=True, key="box")
    r1c2.plotly_chart(make_corr(dfa), use_container_width=True, key="corr")
    if SINGLE:
        # 'by node' bars and the pooled regime scatter compare nodes against
        # each other -- meaningless with a single classroom. The within-node
        # regime scatter in Section 03 covers this case instead.
        st.caption("교실이 1개라 노드 간 비교 차트(CO₂/VOC by node · pooled 레짐 산점도)는 "
                   "생략했습니다. 자기 기준 레짐은 Section 03에서 확인하세요.")
    else:
        # row 2: CO2+VOC by node (stacked, left) | CO2-VOC regime scatter (right)  (1:2)
        r2c1, r2c2 = st.columns([1, 2])
        with r2c1:
            st.plotly_chart(make_target_by_node(dfa, labels, "co2"),
                            use_container_width=True, key="co2_bar")
            st.plotly_chart(make_target_by_node(dfa, labels, "voc"),
                            use_container_width=True, key="voc_bar")
        r2c2.plotly_chart(make_regime_scatter(dfa, labels, latest),
                          use_container_width=True, key="regime")

# ---- Section 3: time series + per-node regime ----
header("03", "Time series by node", "ts")
if SINGLE:
    sel = nodes[0]                      # nothing to select
else:
    sel = st.selectbox("Select node", nodes,
                       format_func=lambda n: label_of(n, labels), key="ts_node")
dfn = df[df["node"] == sel].tail(60)
st.plotly_chart(make_timeseries(dfn), use_container_width=True, key="ts")
# per-node regime scatter | vision occupancy crosshair map  (2 columns)
r3a, r3b = st.columns(2)
r3a.plotly_chart(make_node_regime_scatter(dfa, sel, labels, latest),
                 use_container_width=True, key="node_regime")
with r3b:
    render_vision_panel(sel, labels)
st.caption("좌: 선택 노드의 '자기 기준'(노드별 RobustScaling) — 전체 비교는 Section 02의 "
           "pooled 산점도. 우: 같은 교실(라벨) 비전 노드의 재실 탐지 — 깜빡이는 조준선은 "
           "최근 버킷 '최대 인원 시점'의 위치(c), 수치는 5분 버킷 통계(평균/중앙값/최대). "
           "영상은 전송·저장되지 않습니다(좌표만 수집).")

# ---- Section 4: recent rows ----
header("04", "Recent records", "ts")
recent = df[df["node"] == sel][["recv_time"] + SENSOR_KEYS].tail(5).iloc[::-1]
fmt = {k: ("{:.0f}" if k in ("voc", "nox", "co2") else "{:.1f}")
       for k in SENSOR_KEYS}
st.dataframe(recent.style.format(fmt), use_container_width=True, hide_index=True)

# ---- Section 5: data export ----
header("05", "Data export (CSV)", "export")

# (5-1) full download -- quick backup
csv_all = load_df(limit=10_000_000)        # effectively all
st.download_button(
    "Download all data (CSV)",
    data=csv_all.to_csv(index=False).encode("utf-8-sig"),
    file_name=f"sensor_all_{df['recv_time'].max()[:10]}.csv",
    mime="text/csv",
)

# (5-2) merged analysis download -- env x occupancy, join on (bucket, room)
mrg = load_merged_analysis()
if not mrg.empty:
    rooms = mrg["room"].nunique()
    st.download_button(
        f"Download merged env x occupancy CSV ({len(mrg):,} rows / {rooms} rooms)",
        data=mrg.to_csv(index=False).encode("utf-8-sig"),
        file_name=f"env_occ_merged_{mrg['t_kst'].max()[:10]}.csv",
        mime="text/csv",
        key="dl_merged",
        help="재실 x CO2 상관 분석용. (버킷시각, 교실) 정확 조인, "
             "occ 버킷 n>=25 품질 필터 적용. 상관은 Spearman 권장(포화형 계수 대비).",
    )
elif _occ_table_exists():
    st.caption("Merged export: no matching (bucket, room) rows yet -- "
               "needs both env and vision nodes publishing with NTP time.")


# (5-2b) vision occupancy raw download -- full occupancy schema as stored
def load_occ_all() -> pd.DataFrame:
    if not _occ_table_exists():
        return pd.DataFrame()
    sql = ("SELECT datetime(ts,'+9 hours') AS recv_time_kst, ts AS ts_utc, "
           "node, occ AS occ_mean, occ_med, occ_max, occ_last, cents, w, n "
           "FROM occupancy ORDER BY id")
    with closing(sqlite3.connect(DB)) as con:
        return pd.read_sql_query(sql, con)


occ_all = load_occ_all()
if not occ_all.empty:
    occ_all.insert(3, "room", occ_all["node"].map(labels).fillna(""))
    st.download_button(
        f"Download vision occupancy CSV ({len(occ_all):,} rows / "
        f"{occ_all['node'].nunique()} nodes)",
        data=occ_all.to_csv(index=False).encode("utf-8-sig"),
        file_name=f"occupancy_all_{str(occ_all['recv_time_kst'].max())[:10]}.csv",
        mime="text/csv",
        key="dl_occ_raw",
        help="occupancy 테이블 원본 전체. cents=최대 인원 시점 centroid JSON(w 좌표계), "
             "n=버킷 내 유효 샘플 수(정상 ~30, 낮으면 저품질 버킷). "
             "병합 CSV와 달리 품질 필터 없이 전 행 포함 — 결측/장애 구간 분석에도 사용.",
    )

# (5-3) date-range download -- date picker + hour dropdown
st.markdown("<div class='field-label'>Export by date range (KST)</div>",
            unsafe_allow_html=True)

lo, hi = get_time_bounds()
if lo and hi:
    d1, d2, d3, d4 = st.columns(4)
    start_d = d1.date_input("Start date", value=lo.date(),
                            min_value=lo.date(), max_value=hi.date(), key="sd")
    start_h = d2.selectbox("Start hour", list(range(24)), index=0,
                           format_func=lambda h: f"{h:02d}:00", key="sh")
    end_d   = d3.date_input("End date", value=hi.date(),
                            min_value=lo.date(), max_value=hi.date(), key="ed")
    end_h   = d4.selectbox("End hour", list(range(24)), index=23,
                           format_func=lambda h: f"{h:02d}:00", key="eh")

    start_dt = datetime.combine(start_d, time(start_h, 0, 0))
    end_dt   = datetime.combine(end_d,   time(end_h, 59, 59))

    if start_dt > end_dt:
        st.warning("Start is later than end. Check the range.")
    else:
        rng = query_range(start_dt, end_dt)
        n_rows = len(rng)
        st.caption(f"Range: {start_dt:%Y-%m-%d %H:00} ~ {end_dt:%Y-%m-%d %H:00}"
                   f"   -   {n_rows:,} rows")
        st.download_button(
            f"Download range CSV ({n_rows:,} rows)",
            data=rng.to_csv(index=False).encode("utf-8-sig"),
            file_name=f"sensor_{start_dt:%Y%m%d_%H}-{end_dt:%Y%m%d_%H}.csv",
            mime="text/csv",
            disabled=(n_rows == 0),
            key="dl_range",
        )
        if n_rows == 0:
            st.info("No data in the selected range.")
else:
    st.caption("Range export becomes available once data accumulates.")


# ---- Section 6: data reset (clear table, with auto-backup) ----
header("06", "Data reset", "export")
with st.expander("Clear all collected data (DANGER)", expanded=False):
    st.warning(
        "This empties the 'readings' table. hub.py keeps running and will "
        "store new data into the now-empty table. A CSV backup is saved "
        "automatically before deletion."
    )
    try:
        with closing(sqlite3.connect(DB)) as con:
            total_rows = con.execute("SELECT COUNT(*) FROM readings").fetchone()[0]
    except Exception:
        total_rows = 0
    st.caption(f"Current rows: {total_rows:,}")

    confirm = st.checkbox("I understand this cannot be undone", key="reset_confirm")

    if st.button("Backup + Clear table", type="primary",
                 disabled=(not confirm or total_rows == 0), key="reset_btn"):
        try:
            # 1) auto-backup: save full CSV next to the DB
            backup_df = load_df(limit=10_000_000)
            stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            backup_path = os.path.join(os.path.dirname(os.path.abspath(DB)) or ".",
                                       f"sensor_backup_{stamp}.csv")
            backup_df.to_csv(backup_path, index=False, encoding="utf-8-sig")

            # 2) clear table (hub.py untouched; it keeps writing new rows)
            with closing(sqlite3.connect(DB)) as con:
                con.execute("DELETE FROM readings")
                con.commit()
            try:
                with closing(sqlite3.connect(DB, timeout=2)) as con:
                    con.execute("VACUUM")
            except Exception:
                pass
            load_df.clear()                    # drop cached data so UI refreshes

            st.success(f"Cleared {total_rows:,} rows. Backup saved: {backup_path}")
            st.download_button(
                "Download the backup CSV",
                data=backup_df.to_csv(index=False).encode("utf-8-sig"),
                file_name=f"sensor_backup_{stamp}.csv",
                mime="text/csv",
                key="dl_backup",
            )
            st.info("Refresh (or wait for auto-refresh) to see the empty dashboard.")
        except Exception as e:
            st.error(f"Reset failed: {e}")
